euroc_data_publisher:
  ros__parameters:
    # IMU Configuration
    imu:
      sensor_type: "imu"
      comment: "VI-Sensor IMU (ADIS16448)"
      
      # Publishing rate
      rate_hz: 200.0
      
      # Sensor extrinsics wrt. the body-frame (row-major 4x4 matrix)
      T_BS: [
        1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0,
        0.0, 0.0, 0.0, 1.0
      ]
      
      # Inertial sensor noise model parameters (static)
      gyroscope_noise_density: 1.6968e-04        # [rad/s/sqrt(Hz)] (gyro "white noise")
      gyroscope_random_walk: 1.9393e-05          # [rad/s^2/sqrt(Hz)] (gyro bias diffusion)
      accelerometer_noise_density: 2.0000e-3     # [m/s^2/sqrt(Hz)] (accel "white noise")
      accelerometer_random_walk: 3.0000e-3       # [m/s^3/sqrt(Hz)] (accel bias diffusion)
